name: ReFlex Library - Build & Test

on: 
  # make this workflow reusable
  workflow_call:
    outputs:
      artifact_name:
        description: "name of the artifact that has been uploaded"
        value: ${{ jobs.test-library.outputs.artifact_name }}
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, edited, synchronize ]
    branches:
      - main
    # this workflow can be triggered manually
  workflow_dispatch:

jobs:
  build-library:
    uses: ./.github/workflows/library-build.yml   
  test-library:
    runs-on: windows-latest
    needs: build-library
    name: library
    env:
      artifact_name: .NET Test Report (ReFlex Library)
    outputs:
      artifact_name: ${{ env.artifact_name }}
    steps:
      - name: install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
      - name: Install Required Tools
        run: |
          dotnet new tool-manifest --force
          dotnet tool install dotnet-reportgenerator-globaltool
      - name: restore build artifacts
        uses: actions/cache/restore@v3
        id: cache-library-build
        with:
          path: ${{ needs.build-library.outputs.cache_path }}
          key: ${{ needs.build-library.outputs.cache_key }}      
      - name: execute tests and with code coverage
        run: dotnet test --collect:"XPlat Code Coverage" --results-directory:${{ github.workspace }}/test/artifacts/coverage-net/cobertura/
      - name: generate report
        run: dotnet reportgenerator -reports:"${{ github.workspace }}/test/artifacts/coverage-net/cobertura/**/coverage.cobertura.xml" -targetdir:"${{ github.workspace }}/test/artifacts/coverage-net/report" -reporttypes:"Html_Light;HtmlSummary;Cobertura;XML;XMLSummary;JsonSummary;MarkdownSummaryGithub;Badges -title:"ReFlex - Library" -assemblyfilters:"+ReFlex.*;-*.Test"
      - name: Attach Report as Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_name }}
          path: ${{ github.workspace }}/test/artifacts/coverage-net/report